[package]
name = "trace-viewer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tv"
path = "src/main.rs"

[lib]
name = "trace_viewer"
path = "src/lib.rs"

[dependencies]
imgui = { version = "0.12", features = ["tables-api"] }
imgui-sys = { version = "0.12", features = ["freetype"] }
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }
metal = "0.33"
raw-window-metal = "1"
raw-window-handle = "0.6"
core-graphics-types = "0.2"
memchr = "2"
flate2 = { version = "1", features = ["zlib-ng"], default-features = false }
libdeflater = "1"
tar = "0.4"
memmap2 = "0.9"

[profile.dev-release]
inherits = "release"
opt-level = 2
lto = false
strip = false
codegen-units = 16
incremental = true

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 4
